### ISSUE TITLE
Column reset on restart of thunderbird after update

### ISSUE THREAD

**Issue by rachelnethery** [protz/thunderbird-conversations#1426]
* **Thunderbird version:**
* **Thunderbird Conversation version:**
* **Operating System:**

**What did you do?**
Since the Thunderbird update, every time I restart Thunderbird, the "between" column appears in my inbox. I remove it manually, but then when I restart it appears again. This never happened before the update.

**What did you expect to happen?**
If the between column is manually removed from inbox, it should stay gone upon restart.

**What actually happened?**
Between column always reappears.

**Comment by rachelnethery** [comment]
Sorry, I didn't see the header at the top of the format.

Thunderbird version: 68.4.1
Thunderbird conversation version: 3.0.10
OS: Mac High Sierra version 10.13.6

**Comment by Standard8** [comment]
I've been seeing something similar as well, not sure what it is yet.

Does it occur every time for you, or just when you restart on a folder that you've not restarted on before?

**Comment by rachelnethery** [comment]
Thanks for your quick response! It does occur every time I exit Thunderbird and restart, even on the same folder.

**Comment by Tha14** [comment]
Can also verify that this happens in 68.4.1 and it is quite annoying.

**Comment by fridgelord** [comment]
Hi, to add: "Between" column is always moved to the left-most position after restart even if it was manually moved to other place.

**Comment by WalZyl** [comment]
@Standard8 Although switched off before closing TB, "Between" column re-appears after TB restart (i) always in the first column of and (ii) always but only if while closing TB the tab containing inbox was open/in focus. If another tab, e.g. Options or Add-on Manager, was open while closing TB, after re-start the "Between" column isn't displayed (as expected).   - That what I see here (TB 68.4.1; TB conversations 3.0.10)

**Comment by Standard8** [comment]
I'm actually pondering dropping the between column altogether, but I have no idea of how many people actually use/want it.

I suspect this is an issue in Thunderbird, but tracking it down might be hard... I will try and have a look soon, but I can't promise timing.

**Comment by Standard8** [comment]
I've just seen something on startup - Thunderbird started and visibly after approximately a second, the column was added.

I wonder if Conversations is telling Thunderbird to add the column (as it should do), but it is ignoring or at least not respecting previous settings to not display it.

**Comment by fridgelord** [comment]
> I'm actually pondering dropping the between column altogether, but I have no idea of how many people actually use/want it.

I believe Between column is one the items which are the essence of Conversations. It was originally added to help mimic gmail's way of displaying threads (not as a tree, but one line per conversation in message list pane) - thanks to it you can easily see all the senders and addressees of a whole thread. 

>I've just seen something on startup - Thunderbird started and visibly after approximately a second, the column was added.

Can confirm the delay.

**Comment by Standard8** [comment]
I'm now pretty convinced this is a Thunderbird issue. As far as I can tell, Conversations is doing all the right things, I think it is just that Thunderbird isn't handling it right.

The Thunderbird bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1609378. I'm hopefully going to get time to do a bit more poking on that later today after I've done a few things here and reviewed the outstanding PR.

**Comment by Tha14** [comment]
This stopped being an issue after the update to 68.4.2
Should verify that it is fixed now and you should close this issue.

**Comment by Standard8** [comment]
I suspect it is a timing issue, maybe relating to the order in which add-ons are installed, or something like that. The update to 68.4.2 may have also triggered a lightning update which could also alter some of the timing.

I've also checked the logs for the Thunderbird update, and there's nothing obvious that would affect this.

Therefore I doubt that this has just gone away by itself, and it might have just gone quiet for you for now.

**Comment by Tha14** [comment]
Sounds reasonable. I would like to not that it is currently gone on all 5 of the devices that the issue was appearing at. If it comes back I'll make sure to include logs. Thanks.

**Comment by Standard8** [comment]
At this stage I don't think more logs will help.

I think the problem is a combination of how we're adding columns into Thunderbird, and how Thunderbird is managing the state of those columns, and I'm hoping to look into it more at the weekend, but it depends what time I get.

**Comment by WalZyl** [comment]
I confirm that the issue is still present in 68.4.2.

**Comment by Standard8** [comment]
I've just landed https://github.com/protz/thunderbird-conversations/commit/de0d952785c0ca72ae1daf1f2d589eb6950b87e3 and posted a new version (3.0.12) for review by the add-ons team.

The fix is based on something Enigmail did, though I had to add a slight delay on startup to get it to fire properly. I'm hoping it helps, it might not be 100% perfect.

I've also just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1615801 for adding a proper API to Thunderbird, which will hopefully resolve some of these issues by having better integration.

**Comment by Standard8** [comment]
3.0.12 was approved sometime in the last 24 hours, so it should be available now. I'd appreciate knowing how much this helps. I realise it might not be 100% perfect as it is a big work around.

**Comment by Tha14** [comment]
> 
> 
> 3.0.12 was approved sometime in the last 24 hours, so it should be available now. I'd appreciate knowing how much this helps. I realise it might not be 100% perfect as it is a big work around.

Already updated to it couple hours ago and so far the columns are loading correctly on all systems. Thanks for the quick fix.

**Comment by WalZyl** [comment]
I'm reporting while having only one (Inbox - unified folders, threaded view) tab open in TB 68.5.0, Conversation 3.0.12:
- Between col (at any col position) is deselected before TB quits 
   After re-start, Between col  disappears - the delay is visible.
   Conclusion: If deselected - after restart, Between col remains deselected.
- Between col NOT deselected - but in the third, forth ... col position
   After restart, it re-appears as second col !
   Conclusion: TB is moving the Between col after restart to the second position (from left)

**Overall conclusion**: if deselected (off),  Between coll will be off after restart. If active in any col, it will reappear only in the second col position. The work around (delay) is visible. It's definitely a TB interface problem with / beyond sync and timing.  I support your request for a appropriate TB API.

An addition: TB is NOT maintaining the width of the cols after restart - another TB issue, I guess.

**Comment by Slater91** [comment]
Alas the workaround does not seem to work in my case. The "between" column keeps on reappearing after a restart and then it stays in place. I'm using Thunderbird 68.0.5 on Linux with Conversations 3.0.12.

**Comment by ahsanhussain** [comment]
I'm using Thunderbird 68.4.1 with Conversations and the same is happening for me.

**Comment by Standard8** [comment]
Hi, unfortunately we've done what we can within the extension, so this is going to remain for a bit.

I think the main way this will get fixed is to write a specific WebExtension API in Thunderbird that will handle the column properly, and not throw away information. I suspect that may be difficult, but I'm not sure.

No need to add more "me too" comments. We know this is an issue, but unfortunately needs time.

**Comment by JosifJosif** [comment]
Sorry for another "me too" comment- but mine situation is a little different. It is more like this: [](http://forums.mozillazine.org/viewtopic.php?f=28&t=3000527)


Every time I open Thunderbird my Inbox is either completely missing Sender Column or is showing the Sender and Recipient but without data. To fix that I just have to switch to some other folder and go back to Inbox. And if the Sender was completely absent and I would not switch to some other folder but close the Thunderbird with the Sender missing, the next time I would open it I would have to copy the Columns layout from other folder [or fix it manually] - becauase the Sender in Inbox would be both missing and would not be fixeable by going to some other folder. [So my problem is not with Columns switching positions]

And what is "funny", a few weeks ago some update seemed to had fixed that for good- even after restoring my operating system from an image and updating to the same version of Thunderbird [although from somewhat older version]. I repeated this 3 times because I had to restore so many time that very same image [as I was having troubles updating my WIndows 10]- but the 4th time it was not fixed [and thus I am stuck again with this bug]

It is apparent to me that it is the updates that trigger this and that they are capable of both fixing and of breaking of Columns

[I am sorry that I cannot give you more specific, like the versions of Thunderbird]

**Comment by fritzw** [comment]
I just experienced a new incarnation of what I suspect might be the same issue, which has not been mentioned yet, so I'm adding it here. Maybe it can help with debugging.

After the last restart of Thunderbird (due to the Update to 68.9.0, 32 bit), the Between column was there **twice**, and both were empty. See attached screenshot.

By the way, I find that column really helpful. I use it all the time and would prefer if you didn't remove it.

![thunderbird-bug-between](https://user-images.githubusercontent.com/3628933/84487284-d06f8080-ac9e-11ea-8b1e-4daee4ba604d.png)

**Comment by Standard8** [comment]
@fritzw I'm not sure how it made it there twice. You might want to try removing Conversations, restarting Thunderbird a couple of times, then installing it again. My suspicion is something in the Thunderbird cache is messed up, even though I've tried to work around that.

**Comment by ahsanhussain** [comment]
Some time ago the issue got automagically fixed. I didn't even do anything. I recently did a fresh Tb 68.8 (64 bit) setup with Conversations version 3.1.6 and it is also working fine for me.

**Comment by despecial** [comment]
Still a problem here. Hope Mozilla will fix this for good.

**Comment by despecial** [comment]
PS: can we get an option to disable "between" column completely. It's pretty annoying to uncheck this every time.

**Comment by despecial** [comment]
PPS: can we get a feedback? 

This bug is super frustrating and the option to disable the column completely would help a little.

**Comment by Tha14** [comment]
> 
> 
> PPS: can we get a feedback?
> 
> This bug is super frustrating and the option to disable the column completely would help a little.

What version of thunderbird are you using? I have not had a problem with that column for a long time now and I am using 78.5.0

**Comment by despecial** [comment]
I am using 78.5.0 and it shows up every time I restart Thunderbird

**Comment by Tha14** [comment]
> 
> 
> I am using 78.5.0 and it shows up every time I restart Thunderbird @Tha14

Hey,
So I tried the addon on a new fresh install and it doesn't cause this for me. Yes, it will sometimes show up for a split second when thunderbird starts but it goes away and doesn't come back. Other than that, on the dropdown where you select the columns I only see Between once. This might not really help but have you also tried using the "Start the setup assistant" button in the addon's options? I had issues with the plugin before since I am using 7 email accounts and that seems to fix all the issues every time. Besides that, does it still do it when you create a new thunderbird profile(at appdata) and install the addon? Cheers

**Comment by despecial** [comment]
Even when I use the start seupt assistant and deactivate the option to add the "between" column it comes back after a restart. Not for a moment, no permanentely. 

I dont have the time to set up a complete new profile. This is my business computer.
Ironically - I had this problem with "send later" addon and after issueing it at their repo, they said they used the code from here to remove their column and it worked after updating.

**Comment by Tha14** [comment]
> 
> 
> Even when I use the start seupt assistant and deactivate the option to add the "between" column it comes back after a restart. Not for a moment, no permanentely.
> 
> I dont have the time to set up a complete new profile. This is my business computer.
> Ironically - I had this problem with "send later" addon and after issueing it at their repo, they said they used the code from here to remove their column and it worked after updating.

Yeah, it has been working fine for everyone else. I am not saying you have to remake everything right now, just a new temp profile with a single email address will suffice to figure out where the problem lies. You are on windows, right?

**Comment by despecial** [comment]
MacOS Mojave. Thunderbird 78.5.0. 
Comes back even after removing the addon completely and re-install it.
So I guess it's not compatible with my profile. Too bad.

**Comment by Tha14** [comment]
> 
> 
> MacOS Mojave. Thunderbird 78.5.0.
> Comes back even after removing the addon completely and re-installing it.
> 
> about:config
> `conversations.betweenColumnVisible > true`
> 
> Obviously, this option doesn't care if you remove the column in the view. I set it to false now.
> 
> edit: seems to be the trick to check if this configuration is set correctly.

That should be false, that's how I have set mine aswell(and unchecked "between" for each mail account inbox since I use the "From" column).

Does at least one of the between columns show up anymore or are they both gone?

**Comment by despecial** [comment]
I never had two "between" columns.

**Comment by Tha14** [comment]
> 
> 
> I never had two "between" columns.

My bad, I understood wrong.

**Comment by Standard8** [comment]
We've already started work towards an API built-into Thunderbird. I don't know if it will fix the issue or not (hopefully) but if it doesn't then we at least have more scope for working out a fix. Additionally I'm not sure that API will be available in a release version of Thunderbird until sometime next year.

The only thing I can really offer in the meantime is this:

* Start up Thunderbird.
* Once everything has settled, right click on the between column and remove it.
* Then right-click on the column headers again, at the bottom select "Apply columns to..." -> "Folder and its children..." -> and select your account name twice (so that it gets applied over all the account).
* Repeat the previous steps for all accounts you have, as well as local folders.
* Use Thunderbird for a bit, then shut it down.

That might help, but I can't guarantee it. Conversations should be saving the hidden state in a preference on shutdown and it should then be re-applying it on startup.

**Comment by Standard8** [comment]
In doing some other tests, I noticed that one of my builds/profiles was reproducing this. It looks like the preference I'm using to cache the hidden state isn't always (most of the time? all of the time?) being saved on shutdown, and so when you restart it is in the wrong state.

I've just pushed 45c116d49ec35b0f9cd341f34eada5b2366fcccf to address this. I'm hopefully going to start rolling out a new release with that fix later today.

**Comment by JosifJosif** [comment]
It seems that for me an upgrade to version 78.5.1 (64-bit) has fixed the problem

Finally

**Comment by beglort** [comment]
Sorry to bring it back, still not working for me. The between column keeps reappearing.
Thunderbird 78.6.1; Thunderbird-Conversation 3.2.11 on Linux 5.10.7

**Comment by beglort** [comment]
@sant0s12 I just run the assistant and it still makes the _between_ column reappear, so the bug seems still present. 
Anyway, to be honest, with time I ended up appreciating the _between_ column, I like it now.

**Comment by mfschumann** [comment]
I am seeing the bug with the flatpak version 78.10.1 on fedora linux 34.
@sant0s12: I tried your suggestion of unticking the option in the setup assistant, which fixed the problem at first. But as soon as I manually enabled grouped folders (View->Folders->Grouped), the "between" column came back and reappeared after restarts of thunderbird.

**Comment by taipan-snake** [comment]
Hi, sorry to bring this up again, but this is still an issue. I've experienced it with Thunderbird 78.13.0 and 92.0 beta, both with Thunderbird-Conversations 3.2.33.

I've somehow managed to fix it, but it seems very finicky. Basically, I disabled the default "From" column and enabled the between column, because I thought it actually looked useful. But then the opposite problem happened - on startup, the between column would disappear. So I disabled the between column, and replaced it with the default "From" column again, and now the behaviour seems to have fixed itself for the time being.

**Comment by quentinDupont** [comment]
Same bug with Between column with Thunderbird 78.13.0 and Thunderbird Conversations 3.2.34 

Thanks for this great add-on otherwise :champagne:

**Comment by Taroslord** [comment]
Reminder:
Unfortunately the "Between" column issue is still existing in version 91.3.0 (64-Bit) (Windows).

**Comment by Standard8** [comment]
Reminder:
Unfortunately this is a very complicated issue to fix, with no clear cause and very often is not easy to reproduce on demand, nor work out what the trigger points are. Whilst I'd like to rework the column handling to provide an API, that is a lot of even more difficult work due to how Thunderbird's display of lists works.

Note that the new version of the installer released recently no longer enables the between column by default. Though obviously that won't change things for existing users.

I understand this is annoying when it does get hit. I am limited in what I am able to do here, if I could wave a magic wand then I would.

**Comment by Taroslord** [comment]
> Reminder: Unfortunately this is a very complicated issue to fix, with no clear cause and very often is not easy to reproduce on demand, nor work out what the trigger points are. Whilst I'd like to rework the column handling to provide an API, that is a lot of even more difficult work due to how Thunderbird's display of lists works.
> 
> Note that the new version of the installer released recently no longer enables the between column by default. Though obviously that won't change things for existing users.
> 
> I understand this is annoying when it does get hit. I am limited in what I am able to do here, if I could wave a magic wand then I would.

Thank you for the fast response.
The point is, that unfortunately a reinstallation doesn't change the problem.
Or would it help if the user reinstall everything? I use imap anyway for all my conversations with people.

Best wishes

**Comment by Standard8** [comment]
We have no definite steps to repeat nor things that might help resolve it. If we had, then it might be easier to solve the issue. Unfortunately we don't.

The only thing I think has been suggested before is to hide the column, then use the "Apply Columns To" option to apply to all the folders & children of each account.

**Comment by Taroslord** [comment]
> We have no definite steps to repeat nor things that might help resolve it. If we had, then it might be easier to solve the issue. Unfortunately we don't.
> 
> The only thing I think has been suggested before is to hide the column, then use the "Apply Columns To" option to apply to all the folders & children of each account.

I've already tried this suggestion. First it seemed to work, but then the column appeared at later restart of the application.

**Comment by RomingGnome** [comment]
I can confirm that the reappearing column happens in TB v91.4.0 (64-bit) as well.

**Comment by feimosi** [comment]
I'm struggling with the same issue, it's a fresh install of Thunderbird on a new OS and this still happens, v91.5.1. 
Hiding the column, shrinking so it becomes invisible, "apply columns to" trick, etc. all are for nothing, it always pops back after restarting the app. 
Is there any hack, even involving manual config files modification, to fix this? Can't we just remove this column altogether? Any help would be appreciated.

**Comment by Taroslord** [comment]
> I'm struggling with the same issue, it's a fresh install of Thunderbird on a new OS and this still happens, v91.5.1. Hiding the column, shrinking so it becomes invisible, "apply columns to" trick, etc. all are for nothing, it always pops back after restarting the app. Is there any hack, even involving manual config files modification, to fix this? Can't we just remove this column altogether? Any help would be appreciated.

Still the same here. Really ugly problem. I'm using the same version like @feimosi and open also for any any help.

**Comment by feimosi** [comment]
I came up with a hacky workaround to fix it for me. For anyone interested, here are the steps:
1) open Thunderbird account settings folder (`~/.thunderbird/<id>.default-release` on Linux)
2) then find the extension file: `extensions/gconversation@xulforum.org.xpi`
3) edit `experiment-api/contactsApi.js` file inside it (protip: vim supports editing inside zip files)
4) remove or comment out code related to `"conversations.betweenColumnVisible"` (it's in two places)
5) save everything and run Thunderbird
5) turn off the Conversations extension auto-updates in Thunderbird add-on settings

Do at your own risk. It worked for me on my setup. I really hope this issue gets fixed one day.

**Comment by Taroslord** [comment]
> I came up with a hacky workaround to fix it for me. For anyone interested, here are the steps:
> 
> 1. open Thunderbird account settings folder (`~/.thunderbird/<id>.default-release` on Linux)
> 2. then find the extension file: `extensions/gconversation@xulforum.org.xpi`
> 3. edit `experiment-api/contactsApi.js` file inside it (protip: vim supports editing inside zip files)
> 4. remove or comment out code related to `"conversations.betweenColumnVisible"` (it's in two places). Alternatively change it to always evaluate to hidden (e.g. `treecol.setAttribute("hidden", "true")`)
> 5. save everything and run Thunderbird
> 6. turn off the Conversations extension auto-updates in Thunderbird add-on settings
> 
> Do at your own risk. It worked for me on my setup. I really hope this issue gets fixed one day.

Thank you for the hint. I'm not using Linux. On Windows there's unfortunately no such file nor one with a similar name to be edited.

**Comment by Taroslord** [comment]
> @Taroslord it must be somewhere, I believe the extensions handling is the same on any platform. The profile data should be stored in `%AppData%\Thunderbird\` on Windows.

I've found the file at the location you mentioned and was able to do the changes. Seem it works now.
Thank you! :-)

**Comment by Standard8** [comment]
4.0.12 has just been released that adds an option in the add-on settings to disable the between column completely.

I was hoping that we'd be able to get a dedicated Thunderbird API which would also have hopefully fixed this issue, but that is currently delayed, as Thunderbird is currently working on rewriting the message list view.

**Comment by kskollepara** [comment]
Thanks for the great add-on and the above work around as well.

**Comment by Standard8** [comment]
I believe this is no longer an issue with Thunderbird's new table layout that was released sometime in the last year or two.
